# Reusable .NET NuGet Publish Workflow
# Usage in consuming repo:
#   jobs:
#     publish:
#       uses: deepstaging/.github/.github/workflows/dotnet-publish.yml@main
#       with:
#         solution: MyProject.slnx
#       secrets:
#         nuget-api-key: ${{ secrets.NUGET_API_KEY }}

name: .NET Publish

on:
  workflow_call:
    inputs:
      solution:
        description: 'Solution file to build'
        required: false
        type: string
        default: '*.slnx'
      dotnet-version:
        description: '.NET SDK version'
        required: false
        type: string
        default: '9.0.x'
      configuration:
        description: 'Build configuration'
        required: false
        type: string
        default: 'Release'
      package-path:
        description: 'Path pattern for .nupkg files'
        required: false
        type: string
        default: '**/*.nupkg'
      nuget-source:
        description: 'NuGet source URL'
        required: false
        type: string
        default: 'https://api.nuget.org/v3/index.json'
    secrets:
      nuget-api-key:
        description: 'NuGet API key for publishing'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore
        run: dotnet restore ${{ inputs.solution }}

      - name: Build
        run: dotnet build ${{ inputs.solution }} --configuration ${{ inputs.configuration }} --no-restore

      - name: Test
        run: dotnet test ${{ inputs.solution }} --configuration ${{ inputs.configuration }} --no-build --verbosity normal

      - name: Pack
        run: dotnet pack ${{ inputs.solution }} --configuration ${{ inputs.configuration }} --no-build --output ./packages

      - name: Publish to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.nuget-api-key }} --source ${{ inputs.nuget-source }} --skip-duplicate
